upstream data_service {
    server fastapi:8000;
}

upstream auth_service {
    server auth-circuit-breaker:8000;
}


limit_req_zone $binary_remote_addr zone=api_limit:10m rate=20r/m;

limit_req_zone $binary_remote_addr zone=auth_limit:10m rate=15r/s;

log_format  custom_main  '$remote_addr $remote_user [$time_local] "$request" $status $upstream_response_time $request_time request_id';

server {
    listen 80 default_server;
    server_tokens off;

    location /static/ {
        alias /admin-static/;
    }

    location /admin/ {
        proxy_pass http://admin:8000/admin/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /users/ {
        limit_req zone=auth_limit burst=30 nodelay;
        limit_req_status 429;

        proxy_http_version 1.1;
        proxy_set_header  Host $host;
        proxy_set_header  X-Real-IP $remote_addr;
        proxy_set_header  X-Forwarded-Proto http;
        proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header  X-Forwarded-Host $remote_addr;
        proxy_set_header  X-NginX-Proxy true;
        proxy_set_header  X-Request-Id $request_id;
        proxy_set_header  Upgrade $http_upgrade;
        proxy_set_header  Connection "Upgrade";
        proxy_pass        http://auth_service;
        proxy_ssl_session_reuse off;
        proxy_redirect off;
        access_log /var/log/nginx/access.log custom_main;
    }

    location /api/ {
        limit_req zone=api_limit burst=20 nodelay;
        limit_req_status 429;

        proxy_http_version 1.1;
        proxy_set_header  Host $host;
        proxy_set_header  X-Real-IP $remote_addr;
        proxy_set_header  X-Forwarded-Proto http;
        proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header  X-Forwarded-Host $remote_addr;
        proxy_set_header  X-NginX-Proxy true;
        proxy_set_header  Upgrade $http_upgrade;
        proxy_set_header  Connection "Upgrade";
        proxy_pass        http://data_service;
        proxy_ssl_session_reuse off;
        proxy_redirect off;
        access_log /var/log/nginx/access.log custom_main;
    }
}